version: '3.4'

services:
  mysql:
    image: mysql:8.0.26
    container_name: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: 1234
        MYSQL_DATABASE: products
    ports:
        - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password